### ISSUE TITLE
Please consider supporting the struct plugin

### ISSUE THREAD

**Issue by kasimon** [fmenabe/python-dokuwiki#10]
Since the module provides support for the data plugin, you might want to support its successor, the struct plugin, which provides extra api functions to access its metadata: https://www.dokuwiki.org/plugin:struct:remote_api

**Comment by fmenabe** [comment]
Sorry for the late answer.

I basically implement the methods provided by the plugin (in the *struct* branch of this repo). We don't use this plugin and don't really have time to test more. Can you test and validate it work correctly for your use case?
