### ISSUE TITLE
cookie auth doesn't work with HTTPS

### ISSUE THREAD

**Issue by birkenfeld** [fmenabe/python-dokuwiki#14]
My wiki requires cookieAuth, but also is served via HTTPS. Since CookieTransport always inherits from xmlrpclib's Transport, not SafeTransport, this is not possible right now.

When patched to use SafeTransport as a base class, it works fine for HTTPS for me (py2 and py3 variants). So either you need four classes, or a more intelligent switch :)

Thanks!

**Comment by fmenabe** [comment]
This issue make me realize why I [had 302 errors](https://github.com/fmenabe/python-dokuwiki/pull/11#issuecomment-373161869) when using cookies on my wiki (which redirect http to https).

I patch the code for working with http/https and python2/python3 (in the *cookieauth* branch). Before releasing a new version to PyPI, can you confirm it works well for you?

**Comment by birkenfeld** [comment]
Yes, looks good. Thanks!
