### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by ManuelLevi** [fmenabe/python-dokuwiki#15]
Hi,
I'm having some problems logging in. To be as specific as I can be at the moment:
- I've created a user, with the same password, for test purposes;
- I've created the group `api`, and added the user to it;
- I've activated `XPC`;
- I've added both the user and the group in the `remoteuser`param; I've also tried to leave it empty to give acess to everyone;
- I'm accessing through the https url.

Example code (WIKI_URL, username and password are hardcoded a few lines before and have been double checked):
```
import dokuwiki

v = dokuwiki.DokuWiki(WIKI_URL, username, password).xmlrpc_version()
print(v)
```

The output is:
```
Traceback (most recent call last):
  File "/Users/manuellevi/PycharmProjects/deleteme/get_wiki_stats.py", line 5, in <module>
    wiki = dokuwiki.DokuWiki(WIKI_URL, username, password).xmlrpc_version()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dokuwiki.py", line 169, in __init__
    raise DokuWikiError('invalid login or password!')
dokuwiki.DokuWikiError: invalid login or password!
```

Having checked the URL, username and password, could I be missing something?
I'm wondering if I misread something in the docs.

EDIT: running this with `python3 get_wiki_version.py`.

Thanks,
ML

**Comment by fmenabe** [comment]
Can you test this code which use xmlrpc library directly (Python 3):

```
from xmlrpc.client import ServerProxy
from urllib.parse import urlencode

URL = 'WIKI_URL'
USER = 'USER '
PWD = "PASSWORD"

url = '%s/lib/exe/xmlrpc.php?%s' % (URL, urlencode({'u': USER, 'p': PWD}))
proxy = ServerProxy(url)
print(proxy.dokuwiki.getVersion())
# should print something like: Release 2018-04-22b "Greebo"
```

If you have an error, there is probably something missing server side. I'm not the
administrator of our wiki but has access to the files. From our configuration:

```
# $WIKI_HOME/conf/local.php
...
$conf['remote']      = 1;
$conf['remoteuser']  = '@xmlrpcusers';
...

# $WIKI_HOME/conf/users.auth.php
...
***************:********************************:Francois Menabe:**************************:user,xmlrpcusers
...

```

But if it works, there is a problem with this module! I just release a new version and there may be a regression so can you test with the previous version (1.1.0)?

**Comment by ManuelLevi** [comment]
```
>>> wiki = dokuwiki.DokuWiki(wiki_url, username, password).xmlrpc_version()
Traceback (most recent call last):
  File "/Users/manuellevi/PycharmProjects/deleteme/get_wiki_stats.py", line 7, in <module>
    wiki = dokuwiki.DokuWiki(wiki_url, username, password).xmlrpc_version()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dokuwiki.py", line 169, in __init__
    raise DokuWikiError('invalid login or password!')
dokuwiki.DokuWikiError: invalid login or password!
```

```
>>> from xmlrpc.client import ServerProxy
>>> from urllib.parse import urlencode
>>> url = '%s/lib/exe/xmlrpc.php?%s' % (wiki_url, urlencode({'u': username, 'p': password}))
>>> proxy = ServerProxy(url)
>>> print(proxy.dokuwiki.getVersion())
Release 2018-04-22b "Greebo"
```

I've done `pip3 uninstall dokuwiki` and `pip3 install dokuwiki==1.1.0`. I still get the same error.

**Comment by fmenabe** [comment]
The initialization of the ``dokuwiki.DokuWiki`` object execute a call to the [XMLRPC login method](https://www.dokuwiki.org/devel:xmlrpc#dokuwikilogin) (even by default username and password are passed in the URI) and it seems to return *False* in your case (which should not happen).

To confirm it, can you run this:

```
url = '%s/lib/exe/xmlrpc.php?%s' % (wiki_url, urlencode({'u': username, 'p': password}))
proxy = ServerProxy(url)
print(proxy.dokuwiki.getVersion())
print(proxy.dokuwiki.login(username, password))
```

There are three ways to identify to a wiki:                                                                                                                                                                       
                                                                                                                                                                                                                  
* by passing ids as HTTP GET parameter in each requests (what is done in the sample code)                                                                                                                         
* by passing ids in the uri in each requests (https://USER:PASSWORD@FQDN; what is done by default by the library)                                                                                                 
* by using cookie based authentication but this require to log once (this can be set with the ``cookieAuth`` parameter) 

It may be a problem with how username and password are passed by default, can you also try using cookies (with the latest version):

```v = dokuwiki.DokuWiki(url, username, password, cookieAuth=True)```

**Comment by ManuelLevi** [comment]
If I run 
```
url = '%s/lib/exe/xmlrpc.php?%s' % (wiki_url, urlencode({'u': username, 'p': password}))
proxy = ServerProxy(url)
print(proxy.dokuwiki.getVersion())
print(proxy.dokuwiki.login(username, password))
```
I get 
```
Release 2018-04-22b "Greebo"
False
```

If I run `v = dokuwiki.DokuWiki(wiki_url, username, password, cookieAuth=True)`
I get `rpc.client.ProtocolError: <ProtocolError for (redacted, wiki_url)/lib/exe/xmlrpc.php: 301 Moved Permanently>`

**Comment by fmenabe** [comment]
I think there is something wrong with you're server configuration (I also try to reproduce the problem with a [Docker container](https://hub.docker.com/r/bitnami/dokuwiki/) but could not). Username and password seems to be good (as they are passed in the URL by default and you couldn't get the version if they were wrong) so login should not fail.

The 301 when using cookies indicate you have a redirection somewhere (http -> https?) and that's probably what messing up with the login. 

If you have SSL enabled, ensure the URL you use start with https. Also check your configuration (apache/nginx/htaccess/...) and your logs for some informations.

**Comment by joao8tunes** [comment]
We assume you created a **"bot_user"** user with a **"bot_passwd"** password, and that this **"bot_user"** has read permission to the namespace you want to access via the API. We also assume that you have not enabled any CAPTCHA based login security method since you will be accessing the Wiki with a robot. Honestly, I believe that CAPTCHA or something like that is your real problem.

If you want to access a _"some_page"_ page that is in the _"some_namespace"_ namespace, i.e. _"some_namespace:some_page"_, then you can do something like on the following code to retrieve information from _"some_page"_. If the page you are accessing is static, then you can also use _**"wiki.pages.get()"**_ instead of **_"wiki.pages.html()"_**, which does not require the BeautifulSoup module.

```
from dokuwiki import DokuWiki, DokuWikiError
from bs4 import BeautifulSoup

# Replace with your wiki's host here, but do not use URLs like 'https://wiki.example.com/doku.php?id=...':
WIKI_URL = 'https://wiki.example.com'

# Replace with your bot username:
USER = 'bot_user'

# Replace with your bot password:
PASSWORD = 'bot_passwd'

try:
    # Connecting to DokuWiki API:
    wiki = DokuWiki(WIKI_URL, USER, PASSWORD)

    # Retrieving a wiki page by 'namespace:page', not by URLs:
    html = wiki.pages.html('some_namespace:some_page')

    # You can use BeautifulSoup to crawler HTML data:
    soup = BeautifulSoup(html, "html.parser")

    # Selecting a 'h1' tag by 'id' using BeautifulSoup module:
    selector = soup.find('h1', {'id': 'some_id'})

    # Printing text from the selected tag:
    print(selector.text)
except (DokuWikiError, Exception) as err:
    print('unable to connect: %s' % err)

```

**Comment by fmenabe** [comment]
Did you manage do get it working?

Someone else (#16) have the same problem and I push a commit (in the [login](https://github.com/fmenabe/python-dokuwiki/tree/login) branch) that prevent login in the constructor for simple authentication. This should solve the problem (can you test and confirm it?).
