### ISSUE TITLE
ProtocolError 412 Precondition Failed

### ISSUE THREAD

**Issue by joseanrey** [fmenabe/python-dokuwiki#17]
Hi,
I get this error message in 3 different Dokuwiki sites when I try to create a new connection:

wiki = dokuwiki.DokuWiki('HTTPS-URL','USER','PASSWORD')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/PycharmProjects/test/venv/lib/python3.7/site-packages/dokuwiki.py", line 173, in __init__
    self.version
  File "/home/user/PycharmProjects/test/venv/lib/python3.7/site-packages/dokuwiki.py", line 210, in version
    return self.send('dokuwiki.getVersion')
  File "/home/user/PycharmProjects/test/venv/lib/python3.7/site-packages/dokuwiki.py", line 196, in send
    return method(*args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for USER:PASSWORD@HTTPS-URL/lib/exe/xmlrpc.php: 412 Precondition Failed>

Thanks, Jose

**Comment by RaphaelWimmer** [comment]
Hmm, never had this problem. It seems that the 412 error indicates problems with file/path permissions on the server.
So, this is probably not a bug in python-dokuwiki but a configuration issue with your server.

**Comment by fmenabe** [comment]
I can't reproduce this error on the wiki of my company.  I also launch a docker container with valid SSL certificates and can't reproduce either ... So this will be hard to debug from my side!

For what I quickly found on the web, [412 errors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412) indicates that access to the target resource has been denied which let my think there is something blocking server side. I also found [this](https://kb.bodhost.com/how-to-deal-with-the-error-412-precondition-failed/), [this](https://www.icdsoft.com/en/kb/view/error_412_precondition_failed_mod_security2) and [this](https://social.microsoft.com/Forums/partner/en-US/45ea1d2c-3b26-492e-a67f-e1961c274b25/error-412-precondition-failed-with-wordpress-fixes?forum=writerbeta) linking it to mod_security (Web Application Firewall). So do you have it activated or any other security system on the wikis you tried?

By default login and password are passed through the URL so maybe that's the problem. You could try to set  `cookieAuth` parameter which allows to pass username and password through headers instead.

```
wiki = dokuwiki.DokuWiki('HTTPS-URL','USER','PASSWORD', cookieAuth=True)
```

If this don't work, can you try the sample code from [this comment](https://github.com/fmenabe/python-dokuwiki/issues/15#issuecomment-506970252)? It tries a connection using Python XMLRPC module directly and may throw more informations (or not).

thanks @RaphaelWimmer, see your response after writing mine!

**Comment by joseanrey** [comment]
Thank you so much!!

My hosting provider was blocking my xmlrpc.php file (some mod_security rule for Wordpress in Cpanel).

It was not a bug

Sorry about this mess :)
Thanks, Jose
