### ISSUE TITLE
ImportError: No module named docuwiki

### ISSUE THREAD

**Issue by scaruso** [fmenabe/python-dokuwiki#20]
Hi François,

this module could be very useful.

I installed the module via:

`pip install docuwiki`

and through the `pip list` I check the installation.

I then used tried to import the module but I get this error:

```
# python
Python 2.7.5 (default, Jun 20 2019, 20:27:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docuwiki
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named docuwiki
>>>
```

Can you help me to solve this?

Thanks,
Sara

**Comment by fmenabe** [comment]
Hi Sara, 

The module is named ``dokuwiki`` (with a k), is it the problem or is it just a typo filling the issue?

**Comment by scaruso** [comment]
Hi François,

I beg your pardon but I was really convinced that I wrote well.
It must have been time.

But now I get this error:

`dokuwiki.DokuWikiError: <Fault -32605: 'XML-RPC server not enabled.'>`

How can I solve this?

**Comment by fmenabe** [comment]
This module use the XML-RPC protocol which must be enabled on the Dokuwiki server. You can find the documentation [here](https://www.dokuwiki.org/devel:xmlrpc).
