### ISSUE TITLE
Trying to add medias throws "dokuwiki.DokuWikiError: <Fault 1: "You don't have permissions to upload files.">"

### ISSUE THREAD

**Issue by nickgreen43** [fmenabe/python-dokuwiki#27]
This worked last month but I just moved to a new laptop and now am getting the below traceback... tried figuring out XML-RCP config but have had no luck; I didn't have to do this on my old PC so am wondering what went wrong in moving.

I'm running PHP 7.3.33 and have `if(!$conf['remote']) die((new IXR_Error(-32605, "XML-RPC server not enabled."))->getXml());
` in my xmlrpc.php file

```
Traceback (most recent call last):
  File "C:\Users\PycharmProjects\MiscTools\venv\Lib\site-packages\dokuwiki.py", line 197, in send
    return method(*args)
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\xmlrpc\client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\xmlrpc\client.py", line 1464, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\xmlrpc\client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\xmlrpc\client.py", line 1182, in single_request
    return self.parse_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\xmlrpc\client.py", line 1354, in parse_response
    return u.close()
           ^^^^^^^^^
  File "C:\Python311\Lib\xmlrpc\client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "You don't have permissions to upload files.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PycharmProjects\MiscTools\dokuwikiproject.py", line 30, in <module>
    wiki.medias.add('wiki:' + file, file, overwrite=True)
  File "C:\Users\\PycharmProjects\MiscTools\venv\Lib\site-packages\dokuwiki.py", line 452, in add
    self._dokuwiki.send('wiki.putAttachment', media,
  File "C:\Users\\PycharmProjects\MiscTools\venv\Lib\site-packages\dokuwiki.py", line 203, in send
    raise DokuWikiError(err)
dokuwiki.DokuWikiError: <Fault 1: "You don't have permissions to upload files.">
```

**Comment by fmenabe** [comment]
When I searched on dokuwiki code for the error, I ended [here](https://github.com/splitbrain/dokuwiki/blob/master/inc/media.php#L422). Then I searched for *AUTH_UPLOAD* (which is just a constant defined [here](https://github.com/splitbrain/dokuwiki/blob/master/inc/defines.php#L14)) on a search engine and ended on the Dokuwiki page for [ACLs](https://www.dokuwiki.org/acl).

You should check you have authorized your user to access resources.

**Comment by deydist** [comment]
> When I searched on dokuwiki code for the error, I ended [here](https://github.com/splitbrain/dokuwiki/blob/master/inc/media.php#L422). Then I searched for _AUTH_UPLOAD_ (which is just a constant defined [here](https://github.com/splitbrain/dokuwiki/blob/master/inc/defines.php#L14)) on a search engine and ended on the Dokuwiki page for [ACLs](https://www.dokuwiki.org/acl).
> 
> You should check you have authorized your user to access resources.

Thanks for the reply! You helped me discover that for some reason since I moved over the URLLIB password parse that had setup was no longer working so its not setup in plain text in Python... Thank you!
